### ISSUE TITLE
It needs to be updated.

### ISSUE THREAD

**Issue by valdeniomarinho** [munsta0/WUClientImprovedImprove#3]
It needs to be updated for improve "items" that are outside the player's inventory, for example a "Guard Tower" you cant carry inside your inventory. Anyway thanks for the development of this mod, it helps a lot.

**Comment by munsta0** [comment]
I would love to tell you yes, but unless you can point me to a piece of code that can know what the client mouse is hovering over, I can't. I've never been able to figure it out.

**Comment by valdeniomarinho** [comment]
One guy called bdew has developed one mod called "Custom Actions" where it uses the hovering feature. He has also alot of other custom targets for actions. You can check the source-code here: https://github.com/bdew-wurm/action
